name: Jira to GitHub

on:
    issues:
      types: [opened, edited]

jobs:
  process_jira_payload:
    runs-on: ubuntu-latest

    steps:
    - name: Decodificar e processar o payload
      run: |
        echo "Decodificando o payload do Jira"
        echo "${{ github.event.inputs.encoded_payload }}" | base64 --decode
        # Aqui você pode adicionar mais lógica para processar o payload
