name: Kafka Confluent Topic Update

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  kafka-confluent-update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install confluent-kafka

      - name: Kafka Confluent Topic Update
        run: |
            python3 /$GITHUB_WORKSPACE/kafka-confluet-update.py j-d-p-r
