name: Kafka Topic Createv2

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: 
      COST-CENTER:
        description: 'Centro de custo'
        required: true
      ENVIRONMENT:
        description: 'Ambiente (TU, TI, TH, PR)'
        type: choice  
        required: true
        options:
        - TU
        - TI
        - TH
        - PR
      DOMAIN:
        description: 'Domínio (Ex: Transacionar)'
        required: true
      NAME-SPACE:
        description: 'Name Space'
        required: true      
      DATA-TYPE:
        description: 'Tipo de dado'
        type: choice
        required: true
        options:
        - Log
        - Etl
        - Cdc
      DATA-NAME:
        description: 'Nome do dado'
        required: true
      RETENTION-MS:
        description: 'Tempo de retenção em milissegundos ( PROD )'
        type: number
        required: false
      MAX-MESSAGE-BYTES:
        description: 'Tamanho máximo da mensagem em bytes ( PROD )'
        type: number
        required: false
      NUM-PARTITIONS:
        description: 'Número de partições'
        type: number
        required: false
      REPLICATION-FACTOR:
        description: 'Fator de replicação'
        type: number
        required: false  

jobs:
  kafka-topic-createv2:
    env:
      DOMAIN: ${{ github.event.inputs.DOMAIN }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
      DATA_TYPE: ${{ github.event.inputs.DATA-TYPE }}
      DATA_NAME: ${{ github.event.inputs.DATA-NAME }}
      RETENTION_MS: ${{ github.event.inputs.RETENTION-MS }}
      MAX_MESSAGE_BYTES: ${{ github.event.inputs.MAX-MESSAGE-BYTES }}
      NUM_PARTITIONS: ${{ github.event.inputs.NUM-PARTITIONS }}
      REPLICATION_FACTOR: ${{ github.event.inputs.REPLICATION-FACTOR }}
      KAFKA_CREDENTIALS: ${{ secrets.KAFKA_CREDENTIALS }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install confluent-kafka
      - name: Kafka Topic Createv2
        run: |
          python3 /$GITHUB_WORKSPACE/kafka-confluent-creatv2.py