name: Triggered by Jira

on:
  repository_dispatch:
    types: [jira_issue_created]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Process Jira Issue
        run: |
          echo "Issue Key: ${{ github.event.client_payload.issue_key }}"
          echo "Issue Summary: ${{ github.event.client_payload.issue_summary }}"
